# Generated by Django 5.2.17 on 2026-09-08 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registered', 'ثبت شده'), ('confirmed', 'تأیید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('returned', 'مرجوع شده')], default='registered', max_length=20)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_irr', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('usd_rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('service_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='orders/items/')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(choices=[('USD', 'دلار'), ('EUR', 'یورو'), ('TRY', 'لیر'), ('GBP', 'پوند'), ('AED', 'درهم')], default='USD', max_length=3)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('admin_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('customer', 'فاکتور مشتری'), ('admin', 'فاکتور ادمین')], max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('profit_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'type'), name='unique_invoice_type_per_order')],
            },
        ),
    ]
