# Generated by Django 5.2.17 on 2026-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='رنگ محصول'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه خدمات'),
        ),
    ]
