# Generated by Django 5.2.17 on 2026-09-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_color_orderitem_service_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_cost',
        ),
    ]
