# Generated by Django 5.2.17 on 2026-09-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_service_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
    ]
