# Generated by Django 5.2.17 on 2026-10-04 07:30

from django.db import migrations, models


from decimal import Decimal

DEFAULTS = {
    "EUR": (15, 10, 0),
    "USD": (20, 10, 12),
    "CAD": (20, 10, 12),
    "TRY": (10, 10, 0),
    "AED": (15, 10, 0),
    "GBP": (0, 0, 0),
}


def backfill_percents(apps, schema_editor):
    """
    اقلام قدیمی فقط درصد افزایش کل را دارند. اگر برابر پیش‌فرض ارز بوده،
    با همان تفکیک واسطه/ادمین/تکس پر می‌شود؛ در غیر این صورت سهم ادمین
    حداکثر ۱۰٪ و بقیه سهم واسطه در نظر گرفته می‌شود. درصد افزایش کل
    (و در نتیجه مبلغ فاکتورهای قبلی) تغییر نمی‌کند.
    """
    OrderItem = apps.get_model("orders", "OrderItem")

    for item in OrderItem.objects.all():
        total = Decimal(item.markup_percent or 0)
        broker, admin, tax = DEFAULTS.get(item.currency, (0, 0, 0))

        if Decimal(broker + admin + tax) != total:
            admin = min(Decimal(10), total)
            tax = Decimal(0)
            broker = total - admin

        item.broker_percent = Decimal(broker)
        item.admin_percent = Decimal(admin)
        item.tax_percent = Decimal(tax)
        item.save(update_fields=["broker_percent", "admin_percent", "tax_percent"])


def recalc_invoice_profit(apps, schema_editor):
    """سود ثبت‌شده در فاکتور ادمین باید فقط سود ادمین باشد."""
    Order = apps.get_model("orders", "Order")
    Invoice = apps.get_model("orders", "Invoice")

    for invoice in Invoice.objects.filter(type="admin"):
        order = Order.objects.get(pk=invoice.order_id)

        if not order.usd_rate or order.usd_rate <= 0:
            continue

        total = Decimal(0)

        for item in order.items.all():
            base = (item.product_price * item.exchange_rate).quantize(Decimal("1")) * item.quantity
            total += (base * item.admin_percent / Decimal(100)).quantize(Decimal("1"))

        invoice.profit_usd = (total / order.usd_rate).quantize(Decimal("0.01"))
        invoice.save(update_fields=["profit_usd"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_status_shipping_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="admin_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="درصد ادمین"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="broker_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="درصد واسطه"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="درصد تکس"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "دلار"),
                    ("EUR", "یورو"),
                    ("TRY", "لیر"),
                    ("GBP", "پوند"),
                    ("AED", "درهم"),
                    ("CAD", "دلار کانادا"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.RunPython(backfill_percents, noop),
        migrations.RunPython(recalc_invoice_profit, noop),
    ]
