# Generated by Django 5.2.17 on 2026-10-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_orderitem_profit_percents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "ثبت شده"),
                    ("preparing", "در حال آماده\u200cسازی"),
                    ("shipped_to_iran", "ارسال به ایران"),
                    ("shipped_to_customer", "ارسال به مشتری"),
                    ("delivered", "تحویل داده شده"),
                    ("cancelled", "لغو شده"),
                ],
                default="registered",
                max_length=20,
            ),
        ),
    ]
